version: '3.8'

services:
  # FRONTEND
  nft-bot:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: nft_bot_container
    restart: always
    ports:
      - "80:80" # Map host 80 to container 80 (Vite Preview)
    depends_on:
      - backend

  # BACKEND
  backend:
    build: ./backend
    container_name: nft_backend
    restart: always
    expose:
      - "3001"
    environment:
      # --- DATABASE SETTINGS ---
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=user
      - DB_PASSWORD=pass
      - DB_NAME=nft_db
      - DB_SSL=false
      - PORT=3001

      # --- APP SETTINGS ---
      # Pass these from the Host Environment (do not hardcode here if using secrets)
      - BOT_TOKEN
      - RECEIVER_TON_ADDRESS_TESTNET
      - TONAPI_KEY