version: '3.8'

services:
  backend:
    build: ./backend
    container_name: nft_backend
    restart: always
    ports:
      - "8080:8080"
    environment:
      - DB_USER=user
      - DB_HOST=db
      - DB_NAME=nft_db
      - DB_PASSWORD=pass
      - DB_PORT=5432
      - BOT_TOKEN=your_bot_token_here
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    container_name: nft_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: nft_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data: